#Configure the Server Port
server:
  port: 8080
  
spring:
  application:
   name: Student-SERVICE 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cgitest
    username: root
    password: root12345

